<nav>
    <ul>
        <li><p class="menu"><a href="index.html">Index</a></p></li>
        <li><p class="menu"><a href="jobs.html">Jobs</a></p></li>
        <li><p class="menu"><a href="apply.html">Apply</a></p></li>
        <li><p class="menu"><a href="about.html">About</a></p></li>
        <li>
            <search>
                <form action="/search-results" method="GET">
                    <label for="searchBar">Search</label>
                    <input type="search" id="searchBar" name="q" onkeyup="requiresJavaScriptLol()" placeholder="Search jobs...">
                    <button type="submit">Search</button>
                </form>
            </search>
        </li>
    </ul>
</nav>