<footer>
    <hr>
    <p>&#169; <em>Linkly</em> (2026) <br> Your connection to the future.
    <br>
    <a href="info@linkly.com">info@linkly.com</a></p>   
    <ul>
        <li><p class="menu"><a href="index.php">About</a></p></li>
        <li><p class="menu"><a href="jobs.php">Index</a></p></li>
        <li><p class="menu"><a href="apply.php">Jobs</a></p></li>
        <li><p class="menu"><a href="about.php">Apply</a></p></li>
    </ul>
</footer>