<footer>
    <hr>
    <p>&#169; <em>Linkly</em> (2026) <br> Your connection to the future.
    <br>
    <a href="info@linkly.com">info@linkly.com</a></p>   
    <ul>
        <li><p class="menu"><a href="index.php">About</a></p></li>
        <li><p class="menu"><a href="jobs.php">Index</a></p></li>
        <li><p class="menu"><a href="apply.php">Jobs</a></p></li>
        <li><p class="menu"><a href="about.php">Apply</a></p></li>
    </ul>
    <ul>
        <li><p class="menu"><a href="https://github.com/106510563/applied-project-part2">GitHub</a></p></li>
        <li><p class="menu"><a href="https://ciarasmith.atlassian.net/?continue=https%3A%2F%2Fciarasmith.atlassian.net%2Fwelcome%2Fsoftware%3FprojectId%3D10033&atlOrigin=eyJpIjoiZDA2ZTYwMDVkOTU2NGZiNjk3NjZiYjMyMzRiMTlhZTIiLCJwIjoiamlyYS1zb2Z0d2FyZSJ9">Jira</a></p></li>
    </ul>
</footer>