<nav>
    <ul>
        <li><p class="menu"><a href="index.php">Index</a></p></li>
        <li><p class="menu"><a href="jobs.php">Jobs</a></p></li>
        <li><p class="menu"><a href="apply.php">Apply</a></p></li>
        <li><p class="menu"><a href="about.php">About</a></p></li>
        <li>
            <search>
                <form action="/search-results" method="GET">
                    <label for="searchBar">Search</label>
                    <input type="search" id="searchBar" name="q" onkeyup="requiresJavaScriptLol()" placeholder="Search jobs...">
                    <button type="submit">Search</button>
                </form>
            </search>
        </li>
        <li><p class="menu"><a href="login.php">Login</a></p></li>
        <li><p class="menu"><a href="signup.php">Signup</a></p></li>
        
    </ul>
</nav>